general {
    # Bloquea la sesión antes de que el sistema entre en suspensión
    before_sleep_cmd = loginctl lock-session 
    # Asegura que el monitor se encienda al despertar
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. Apagar el monitor a los 3 minutos (180 segundos)
listener {
    timeout = 180                                
    on-timeout = hyprctl dispatch dpms off       # Comando para apagar monitores
    on-resume = hyprctl dispatch dpms on        # Lo enciende al detectar actividad
}

# 2. Suspender el sistema a los 15 minutos (900 segundos)
listener {
    timeout = 900                                
    on-timeout = systemctl suspend               # Suspende el equipo
}

# 3. Apagar el sistema a los 25 minutos (1500 segundos)
listener {
    timeout = 1500                               
    on-timeout = systemctl poweroff              # Apaga el equipo por completo
}

